import FreelanceItem from "@/components/FreelanceItem/FreelanceItem";
import Header from "@/components/Header/Header";
import Loading from "@/components/Loading/Loading";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import SearchBox from "../../components/SearchBox/SearchBox";
import axios from "axios";
import { TbError404 } from "react-icons/tb";
import { RiSignalWifiErrorLine } from "react-icons/ri";
export interface ListItemProps {
  projectTitle: string;
  projectDescription: string;
  projectLink: string;
  projectTags: { title: string; link: string }[];
  projectBudget: string;
  name: string;
}

function Search() {
  const router = useRouter();
  const { keyword, sort } = router.query;
  const [list, setList] = useState<ListItemProps[]>([]);
  const [loading, setLoading] = useState<boolean>(true);
  const [error, setError] = useState<boolean>(false);
  const [sortValue, setSort] = useState<string>("");
  const getQueryParams = () => {
    const params = Object.keys(router.query);
    let queries = "";
    for (const param of params) {
      if (!queries.length) {
        queries += `${param}=${router.query[param]}`;
      } else {
        queries += `&${param}=${router.query[param]}`;
      }
    }

    return queries;
  };

  const sortMethods: any = {
    highestPrice: (data: any[]) => {
      return data.sort((a: any, b: any) => {
        if (Number(a.projectBudget) > Number(b.projectBudget)) {
          return -1;
        }
        if (Number(a.projectBudget) < Number(b.projectBudget)) {
          return 1;
        }
        return 0;
      });
    },
    lowestPrice: (data: any[]) => {
      return data.sort((a: any, b: any) => {
        if (Number(a.projectBudget) > Number(b.projectBudget)) {
          return 1;
        }
        if (Number(a.projectBudget) < Number(b.projectBudget)) {
          return -1;
        }
        return 0;
      });
    },
  };

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        const { data: searchedList, status } = await axios.get(
          `/api/search?${getQueryParams()}`
        );
        const sortedList =
          sortMethods[sort ? String(sort) : "highestPrice"](searchedList);
        setList(sortedList);
        setLoading(false);
      } catch (error) {
        console.log(error);
        setError(true);
        setLoading(false);
      }
    };

    setSort(sort ? String(sort) : "highestPrice");

    if (keyword) {
      fetchData();
    }
  }, [keyword]);

  const handleChangeSortValue = (e: any) => {
    const sortedData = sortMethods[e.target.value](list);
    setList(sortedData);
    setSort(e.target.value);
    router.query.sort = e.target.value;
    router.push(router);
  };

  const handleSearchSubmit = () => {
    setList([]);
  };

  const renderLoading = () => {
    return loading ? (
      <>
        <Loading />
        <Loading />
        <Loading />
      </>
    ) : (
      <></>
    );
  };

  const renderList = () => {
    if (!loading && !error && list.length) {
      return list.map((item, index: number) => {
        return <FreelanceItem item={item} key={index} />;
      });
    } else if (!loading && error) {
      return (
        <div className="flex flex-col justify-center w-full h-96 items-center">
          <span>
            <RiSignalWifiErrorLine fontSize={100} className="text-indigo-600" />
          </span>
          <h2 className="text-indigo-500 font-yekan-bold">
            خطایی پیش آمده است. لطفا اطلاع دهید
          </h2>
        </div>
      );
    } else if (!loading && !error && !list.length) {
      return (
        <div className="flex flex-col justify-center w-full h-96 items-center">
          <span>
            <TbError404 fontSize={100} className="text-indigo-600" />
          </span>
          <h2 className="text-indigo-500 font-yekan-bold">
            نتونستیم چیزی که میخوای رو پیدا کنیم
          </h2>
        </div>
      );
    }

    return [];
  };
  return (
    <>
      <Head>
        <title>جستجوی موقعیت شغلی مربوط به {keyword}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`w-full flex flex-col items-center bg-gradient-to-r  bg-slate-100 dark:from-slate-900 dark:to-slate-700`}
      >
        <Header />
        <div className="relative flex flex-col items-center justify-center w-11/12 p-10 bg-white rounded-md md:w-2/3 h- dark:bg-slate-900">
          <div className="flex justify-between w-full">
            <h1 className="text-xl text-indigo-500 font-yekan-bold">
              جستجو کلیدواژه `{keyword}`
            </h1>
            <span className="text-sm font-yekan-regular text-slate-400">
              {list.length ? `${list.length} مورد پیدا شد` : ""}
            </span>
          </div>
          <div className="w-full py-5">
            <SearchBox onFormSubmit={handleSearchSubmit} />
            <br />
            <form action="">
              <div className="flex items-center w-full gap-3">
                <div className="w-2/6 md:w-1/6">
                  <span className="font-yekan-regular">مرتب سازی:</span>
                </div>
                <div className="w-4/6 md:w-1/6">
                  <select
                    value={sortValue}
                    disabled={loading}
                    onChange={handleChangeSortValue}
                    className="w-full h-10 rounded-md font-yekan-regular bg-slate-100 dark:bg-slate-700 dark:text-white md:w-96"
                  >
                    {sortValue === "highestPrice" ? (
                      <>
                        <option value="highestPrice">از بیشترین قیمت</option>
                        <option value="lowestPrice">از کمترین قیمت</option>
                      </>
                    ) : (
                      <>
                        <option value="lowestPrice">از کمترین قیمت</option>
                        <option value="highestPrice">از بیشترین قیمت</option>
                      </>
                    )}
                  </select>
                </div>
              </div>
            </form>
          </div>
          <div className="flex flex-col w-full py-5">
            {renderLoading()}
            {renderList()}
          </div>
        </div>
      </main>
    </>
  );
}

export default Search;
